# Generated by Django 5.0.6 on 2026-06-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Médecin'), ('ADMIN', 'Administrateur')], default='PATIENT', max_length=20),
        ),
    ]
