# Generated by Django 5.0.6 on 2026-06-02 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_full_unique_add_indexes'),
        ('doctors', '0003_alter_doctor_options_alter_specialty_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_doctor__111942_idx',
            old_name='appointmen_doctor__3ec0d7_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_patient_83aa7a_idx',
            old_name='appointmen_patient_95899e_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_status_8fe9d7_idx',
            old_name='appointmen_status_38a96f_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.specialty'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('CANCELLED', 'Annulé'), ('COMPLETED', 'Terminé'), ('NO_SHOW', 'Absent')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='summary',
            field=models.TextField(help_text='Résumé administratif de consultation, sans diagnostic médical détaillé'),
        ),
    ]
