# Generated by Django 5.0.6 on 2026-06-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_languages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['name'], 'verbose_name': 'Spécialité', 'verbose_name_plural': 'Spécialités'},
        ),
        migrations.AlterField(
            model_name='specialty',
            name='keywords',
            field=models.TextField(blank=True, help_text="Mots-clés séparés par des espaces ou virgules, utilisés par l'IA"),
        ),
    ]
