# Generated by Django 5.0.6 on 2026-06-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'Disponibilité', 'verbose_name_plural': 'Disponibilités'},
        ),
        migrations.AlterModelOptions(
            name='timeoff',
            options={'ordering': ['-start_date'], 'verbose_name': 'Indisponibilité', 'verbose_name_plural': 'Indisponibilités'},
        ),
    ]
